/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ProfileImport } from './routes/profile'
import { Route as NotfoundImport } from './routes/notfound'
import { Route as LoginImport } from './routes/login'
import { Route as CallbackImport } from './routes/callback'
import { Route as AboutImport } from './routes/about'
import { Route as AuthenticatedImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexImport } from './routes/_authenticated/index'
import { Route as AuthenticatedSettingSettingImport } from './routes/_authenticated/_setting/setting'
import { Route as AuthenticatedItem2Item2Import } from './routes/_authenticated/_item2/item2'
import { Route as AuthenticatedItem1Item1Import } from './routes/_authenticated/_item1/item1'

// Create/Update Routes

const ProfileRoute = ProfileImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRoute,
} as any)

const NotfoundRoute = NotfoundImport.update({
  id: '/notfound',
  path: '/notfound',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const CallbackRoute = CallbackImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedRoute = AuthenticatedImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedIndexRoute = AuthenticatedIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedSettingSettingRoute =
  AuthenticatedSettingSettingImport.update({
    id: '/_setting/setting',
    path: '/setting',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedItem2Item2Route = AuthenticatedItem2Item2Import.update({
  id: '/_item2/item2',
  path: '/item2',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedItem1Item1Route = AuthenticatedItem1Item1Import.update({
  id: '/_item1/item1',
  path: '/item1',
  getParentRoute: () => AuthenticatedRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/callback': {
      id: '/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof CallbackImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/notfound': {
      id: '/notfound'
      path: '/notfound'
      fullPath: '/notfound'
      preLoaderRoute: typeof NotfoundImport
      parentRoute: typeof rootRoute
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/_item1/item1': {
      id: '/_authenticated/_item1/item1'
      path: '/item1'
      fullPath: '/item1'
      preLoaderRoute: typeof AuthenticatedItem1Item1Import
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/_item2/item2': {
      id: '/_authenticated/_item2/item2'
      path: '/item2'
      fullPath: '/item2'
      preLoaderRoute: typeof AuthenticatedItem2Item2Import
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/_setting/setting': {
      id: '/_authenticated/_setting/setting'
      path: '/setting'
      fullPath: '/setting'
      preLoaderRoute: typeof AuthenticatedSettingSettingImport
      parentRoute: typeof AuthenticatedImport
    }
  }
}

// Create and export the route tree

interface AuthenticatedRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedItem1Item1Route: typeof AuthenticatedItem1Item1Route
  AuthenticatedItem2Item2Route: typeof AuthenticatedItem2Item2Route
  AuthenticatedSettingSettingRoute: typeof AuthenticatedSettingSettingRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedItem1Item1Route: AuthenticatedItem1Item1Route,
  AuthenticatedItem2Item2Route: AuthenticatedItem2Item2Route,
  AuthenticatedSettingSettingRoute: AuthenticatedSettingSettingRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

export interface FileRoutesByFullPath {
  '': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/callback': typeof CallbackRoute
  '/login': typeof LoginRoute
  '/notfound': typeof NotfoundRoute
  '/profile': typeof ProfileRoute
  '/': typeof AuthenticatedIndexRoute
  '/item1': typeof AuthenticatedItem1Item1Route
  '/item2': typeof AuthenticatedItem2Item2Route
  '/setting': typeof AuthenticatedSettingSettingRoute
}

export interface FileRoutesByTo {
  '/about': typeof AboutRoute
  '/callback': typeof CallbackRoute
  '/login': typeof LoginRoute
  '/notfound': typeof NotfoundRoute
  '/profile': typeof ProfileRoute
  '/': typeof AuthenticatedIndexRoute
  '/item1': typeof AuthenticatedItem1Item1Route
  '/item2': typeof AuthenticatedItem2Item2Route
  '/setting': typeof AuthenticatedSettingSettingRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/callback': typeof CallbackRoute
  '/login': typeof LoginRoute
  '/notfound': typeof NotfoundRoute
  '/profile': typeof ProfileRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/_item1/item1': typeof AuthenticatedItem1Item1Route
  '/_authenticated/_item2/item2': typeof AuthenticatedItem2Item2Route
  '/_authenticated/_setting/setting': typeof AuthenticatedSettingSettingRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/about'
    | '/callback'
    | '/login'
    | '/notfound'
    | '/profile'
    | '/'
    | '/item1'
    | '/item2'
    | '/setting'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/callback'
    | '/login'
    | '/notfound'
    | '/profile'
    | '/'
    | '/item1'
    | '/item2'
    | '/setting'
  id:
    | '__root__'
    | '/_authenticated'
    | '/about'
    | '/callback'
    | '/login'
    | '/notfound'
    | '/profile'
    | '/_authenticated/'
    | '/_authenticated/_item1/item1'
    | '/_authenticated/_item2/item2'
    | '/_authenticated/_setting/setting'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  CallbackRoute: typeof CallbackRoute
  LoginRoute: typeof LoginRoute
  NotfoundRoute: typeof NotfoundRoute
  ProfileRoute: typeof ProfileRoute
}

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  CallbackRoute: CallbackRoute,
  LoginRoute: LoginRoute,
  NotfoundRoute: NotfoundRoute,
  ProfileRoute: ProfileRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_authenticated",
        "/about",
        "/callback",
        "/login",
        "/notfound",
        "/profile"
      ]
    },
    "/_authenticated": {
      "filePath": "_authenticated.tsx",
      "children": [
        "/_authenticated/",
        "/_authenticated/_item1/item1",
        "/_authenticated/_item2/item2",
        "/_authenticated/_setting/setting"
      ]
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/callback": {
      "filePath": "callback.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/notfound": {
      "filePath": "notfound.tsx"
    },
    "/profile": {
      "filePath": "profile.tsx"
    },
    "/_authenticated/": {
      "filePath": "_authenticated/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/_item1/item1": {
      "filePath": "_authenticated/_item1/item1.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/_item2/item2": {
      "filePath": "_authenticated/_item2/item2.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/_setting/setting": {
      "filePath": "_authenticated/_setting/setting.tsx",
      "parent": "/_authenticated"
    }
  }
}
ROUTE_MANIFEST_END */
